### ISSUE TITLE
update to SDK 1.11.0

### ISSUE THREAD

**Issue by boozook** [pd-rs/crankstart#19]
See [changelog](https://sdk.play.date/changelog/).

- `playdate.menu:getMenuItems()`

**Comment by tjkirch** [comment]
It looks like we're up to SDK 1.12.3 in crankstart :)  https://github.com/pd-rs/crankstart/commit/280936bb953c0467849b34b58c1caa1c790c79fb

**Comment by tjkirch** [comment]
1.13.0 is out now, which is a huge release: https://sdk.play.date/changelog/

Maybe this issue could be repurposed?
