### ISSUE TITLE
Document how to update bindings

### ISSUE THREAD

**Issue by rtsuk** [pd-rs/crankstart#21]

**Comment by tjkirch** [comment]
I'd be up for helping update crankstart to SDK 1.13.0, and I might be able to muddle my way through, but docs would certainly help!

**Comment by rtsuk** [comment]
1. Install the [bindgen-cli](https://rust-lang.github.io/rust-bindgen/introduction.html) and its [dependencies](https://rust-lang.github.io/rust-bindgen/requirements.html).
2. Have the PlayDate SDK installed at `$HOME/Developer/PlaydateSDK`.
3. Run `./scripts/generate_bindings.sh` from the `crankstart` directory.

As far as I know, this has only every been run on a Mac.

**Comment by rtsuk** [comment]
I went through these steps to make sure they were the right ones and it worked so I'm going to push the new bindings.

**Comment by tjkirch** [comment]
Awesome, thanks! I might take a look to see how it works on Linux, too.

**Comment by rtsuk** [comment]
I set this up kinda wrong. I'm not sure the entire target triple is needed, probably just the processor family. That way AArch64 Linux or Mac could use the same bindings.

**Comment by rtsuk** [comment]
Bottom of the readme is fine.

I'll have to check it on Mac after you modify it.
