### ISSUE TITLE
Access to audio API

### ISSUE THREAD

**Issue by tjkirch** [pd-rs/crankstart#32]
The Playdate audio API is huge, but it seems like it could be added in pieces - perhaps SamplePlayer first, for sound effects, then FilePlayer, for music, then manual controls and effects...

**Comment by rtsuk** [comment]
As long as there are no callbacks, making these wrappers is pretty mechanical.

**Comment by tjkirch** [comment]
> As long as there are no callbacks, making these wrappers is pretty mechanical.

For basic audio usage, no callbacks are necessary.  The API supports callbacks for running code when audio playback completes, and for fancier uses like fading, and running upon headphone/microphone changes.  Those could be added later when we're happy with a callback system.

I did a prototype and got a sound to play with a minimal static SOUND type similar to GRAPHICS, and a bunch of unsafe code that uses the bindings directly.  Now that I know it can work, I think I could make a Sound type that works like Graphics, at least for the basic functionality.  I'll give it a shot.
