### ISSUE TITLE
Text sprites

### ISSUE THREAD

**Issue by tjkirch** [pd-rs/crankstart#35]
I spent quite a while struggling to get sprites and `graphics.draw_text` to work together, finally figuring out that the sprite system clears the whole screen upon `updateAndDrawSprites` even if there are no dirty sprites, and so you have to `draw_text` _after_ that happens.  With crankstart's current structure, I think that can only happen in `draw_sprite` for a sprite with `set_use_custom_draw` (which doesn't feel like the right place, and I've had trouble with segfaults there) or in `draw_fps` (which _definitely_ doesn't feel right and has no useful error return mechanism).

I eventually found a couple dev forum posts, [here](https://devforum.play.date/t/text-dialog-boxes-animated-text/4009/4) and [here](https://devforum.play.date/t/text-is-hidden-invisible/5495/3), that suggest the right path is using a sprite and drawing text inside it.  I got this working in crankstart by adding `Graphics.pushContext` and `Graphics.popContext` and some awful hacks to handle `LCDBitmap` structures.  You can then push, `draw_text` at coordinates relative to that bitmap, and pop; it'll draw inside the bitmap, and when the sprite containing that bitmap is drawn, it'll actually draw and stay.  It's not as nice as Lua with its additional `drawTextInRect` (you have to size the sprite more manually here) but there are hints that `drawTextInRect` might be added to the C API soon-ish.

I wanted to see if anyone has a better method of drawing text _and_ sprites, or if something like this (push/pop context, mainly) would be appropriate to add, and if so, any thoughts about their API as they relates to `Bitmap` vs. `LCDBitmap`.

**Comment by rtsuk** [comment]
You could make a generic method on Sprite that takes an T: FnOnce, does the setup, calls the function, then cleans up.

**Comment by rtsuk** [comment]
That said, set_use_custom_draw does seem like the right approach for this. If you can reproduce the segfaults we should figure out why they occur.

**Comment by tjkirch** [comment]
I've been playing with this a bit more, and I made this helper function to abstract the text sprite stuff:

```rust
// Currently no font:get or getHeight in C API.
const SYSTEM_FONT_HEIGHT: i32 = 18;

fn text_sprite<S>(text: S) -> Result<Sprite>
where
    S: AsRef<str>,
{
    let text = text.as_ref();
    let graphics = Graphics::get();
    let sprite_manager = SpriteManager::get_mut();
    // Currently no getTextTracking C API; assume none has been set.
    let tracking = 0;
    let width = graphics.get_system_text_width(text, tracking)?;
    let mut text_bitmap = graphics.new_bitmap(size2(width, SYSTEM_FONT_HEIGHT), WHITE)?;
    graphics.with_context(&mut text_bitmap, || {
        graphics.draw_text(text, point2(0, 0))?;
        Ok(())
    })?;
    let mut text_sprite = sprite_manager.new_sprite()?;
    text_sprite.set_image(text_bitmap, LCDBitmapFlip::kBitmapUnflipped)?;
    sprite_manager.add_sprite(&text_sprite)?;
    Ok(text_sprite)
}
```

It could probably use a bit more configurability, but you get the gist.

It requires this addition to `impl Graphics` in crankstart:
```rust
    pub fn get_system_text_width(&self, text: &str, tracking: i32) -> Result<i32, Error> {
        let c_text = CString::new(text).map_err(Error::msg)?;
        pd_func_caller!(
            (*self.0).getTextWidth,
            ptr::null_mut(),
            c_text.as_ptr() as *const core::ffi::c_void,
            text.len(),
            PDStringEncoding::kUTF8Encoding,
            tracking,
        )
    }
```
...where the only difference from `Graphics.get_text_width` is the removal of the `Font` argument, since passing null gives you the width using the system font - I think that's intended given [this](https://devforum.play.date/t/getfontheight-does-not-accept-null/2027/2).  (I tried to update `get_text_width` with something like `font: Into<Option<&Font>>` so existing callers not passing an `Option` would work, and passing `None` would give you the system font, but I couldn't figure out the lifetimes.  I think it's worth considering taking `Option<&Font>` in a breaking release of crankstart, since I imagine many people use the system font, and I think there's currently no way to get a reference to the system font to pass in.)

Once you have the `Sprite`, you can `.get_bounds()` if you want to know what the calculated width/height were, and `.move_to` where you want it as usual.  (The center of the text is the anchor point, just like image sprites.)  To update the text, something like this can be used, replacing the assigned bitmap:

```rust
fn update_text<S>(text_sprite: &mut Sprite, text: S) -> Result<()>
where
    S: AsRef<str>,
{
    let text = text.as_ref();
    let graphics = Graphics::get();
    // Currently no getTextTracking C API; assume none has been set.
    let tracking = 0;
    let width = graphics.get_system_text_width(text, tracking)?;
    let mut text_bitmap = graphics.new_bitmap(size2(width, SYSTEM_FONT_HEIGHT), WHITE)?;
    graphics.with_context(&mut text_bitmap, || {
        graphics.draw_text(text, point2(0, 0))?;
        Ok(())
    })?;
    text_sprite.set_image(text_bitmap, LCDBitmapFlip::kBitmapUnflipped)?;
    Ok(())
}
```

I'm wondering if it's worth pursuing a helper type for code like this in crankstart, like a `TextSprite`.  I can't be the only one mixing (dynamic) text and sprites, and it's harder than it should be, I'd say.

(I'm also wondering, more generally, whether something like the Lua SDK's CoreLibs would be useful in crankstart; an "extras" module, perhaps.)

**Comment by tjkirch** [comment]
Cool, I'll work on a couple helpers.  I think a similar pattern would make sense for rotated images, since they're constructed similarly, and changing the rotation is done similarly.  (Taking the bitmap behind a sprite, clearing it or creating a new one, drawing the adjustment.)
