### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by jcornaz** [pd-rs/crankstart#51]
Hi, 

It'd be great to be able to consume `crankstart` and `crankstart-sys` from [crates.io](https://crates.io).

Which would make it easier to consume, and to build other libraries/helpers on top of it.

**Comment by boozook** [comment]
It will be, I hope. 
Crates `crankstart` and `crankstart-sys` is our own. I'll take a look what's wrong and try to publish.


By the way, currently I'm working on the similar project and in a week I want to start publish it, part-to-part. Now I'm not sure if it will be within that org or in a personal account. It would be great to have you participate in the testing, but I have no idea how to notify you.

**Comment by parasyte** [comment]
FWIW, this issue is a good way to notify me on the status of publishing the crate. Either through additional comments or by closing it when completed.

I saw you published a large number of Playdate-related placeholder crates a few months ago, could this be to what you are referring?

**Comment by boozook** [comment]
Definitely yes.

**Comment by boozook** [comment]
Done.

**Comment by jcornaz** [comment]
> Done.

Thank you so much :heart: 

> By the way, currently I'm working on the similar project and in a week I want to start publish it, part-to-part. Now I'm not sure if it will be within that org or in a personal account. It would be great to have you participate in the testing, but I have no idea how to notify you.

I suggest posting an announcement in GitHub discussions: https://github.com/pd-rs/crankstart/discussions/categories/announcements, so that anyone following this repo will be notified (incl. me)

You may also mention the GitHub handle of the people you want to be notified in a discussion, issue, or pull request.  (example: @jcornaz)

I am looking forward to seeing what you are working on :-)
